namespace NeuroScan.Domain.Entities;

public class AnalysisResult : BaseEntity
{
    public Guid MriScanId { get; set; }

    // Model 1 (UNet) Results
    public double CsfVolume { get; set; }      // Cerebrospinal Fluid
    public double GmVolume { get; set; }       // Gray Matter
    public double WmVolume { get; set; }       // White Matter
    public double AsymmetryIndex { get; set; }

    // Model 2 (SegResNet) Results
    public double CsfVolumeModel2 { get; set; }
    public double GmVolumeModel2 { get; set; }
    public double WmVolumeModel2 { get; set; }
    public double AsymmetryIndexModel2 { get; set; }

    // Comparison Metrics
    public double DiceScoreCsf { get; set; }
    public double DiceScoreGm { get; set; }
    public double DiceScoreWm { get; set; }
    public double DisagreementPercentage { get; set; }
    public string? RecommendedModel { get; set; }
    public double ModelConfidence { get; set; }

    public string? MedicalReportText { get; set; } // Generated by OpenAI
    public DateTime AnalyzedAt { get; set; }

    // Navigation property
    public MriScan MriScan { get; set; } = null!;
}
