namespace NeuroScan.Domain.Entities;

public class AnalysisResult : BaseEntity
{
    public Guid MriScanId { get; set; }
    public double CsfVolume { get; set; }      // Cerebrospinal Fluid
    public double GmVolume { get; set; }       // Gray Matter
    public double WmVolume { get; set; }       // White Matter
    public double AsymmetryIndex { get; set; }
    public string? MedicalReportText { get; set; } // Generated by OpenAI
    public DateTime AnalyzedAt { get; set; }

    // Navigation property
    public MriScan MriScan { get; set; } = null!;
}
