<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.*" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.*">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NeuroScan.Application\NeuroScan.Application.csproj" />
    <ProjectReference Include="..\NeuroScan.Infrastructure\NeuroScan.Infrastructure.csproj" />
    <ProjectReference Include="..\NeuroScan.Shared\NeuroScan.Shared.csproj" />
  </ItemGroup>

</Project>
